export const meepoLibs = {
    qrcode: 'qrcode.min.js',
    vconsole: 'vconsole.min.js',
    hammer: 'hammer.min.js',
    swiper: 'swiper-3.4.2.min.js',
    require: 'require.js',
    // xscroll
    xscroll: 'xscroll/xscroll.min.js',
    infinite: 'xscroll/infinite.min.js',
    lazyload: 'xscroll/lazyload.min.js',
    pulldown: 'xscroll/pulldown.min.js',
    pullup: 'xscroll/pullup.min.js',
    scale: 'xscroll/scale.min.js',
    snap: 'xscroll/snap.min.js',
    // plupload
    'plupload.full': 'plupload/plupload.full.min.js',
    plupload: 'plupload/plupload.min.js',
    moxie: 'plupload/moxie.min.js',
    'moxie.swf': 'plupload/Moxie.swf',
    'moxie.xap': 'plupload/Moxie.xap',
    // mescroll
    'mescroll.m': 'mescroll/mescroll.m.js',
    'mescroll': 'mescroll/mescroll.min.js',
    // 拖拽
    draggabilly: 'draggabilly/draggabilly.pkgd.min.js',
    // photoswipe
    photoswipe: 'photoswipe/photoswipe.min.js',
    // clipboard
    clipboard: 'clipboard/clipboard.min.js'
};